apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: lamp-php:latest

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: php-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-root-password
        ports:
        - containerPort: 80
      volumes:
